name: Check for unexpected package-lock.json changes

on:
  # NOTE: Consider using pull_request_target instead to support fork PRs (see: https://github.com/mshick/add-pr-comment/issues/25)
  pull_request:
    paths:
      - 'package-lock.json'
      - '!package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Question package-lock.json change without package.json change
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            This pull request includes a change to the `package-lock.json` without 
            a corresponding change to the `package-lock.json` file. This is generally 
            a sign that your node_modules are out of sync with what is defined in this
            repo. Unless this is an intentional change (for example, a result of 
            running `npm audit fix`), please revert your changes to `package-lock.json`
            and then reset your node_modules with `npm ci`. 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
